add support of virtualkeyboard show and hide
fcitx/fcitx5-qt pull request #43
Opened 2023-07-28 02:26 UTC by linyuxuan123

2023-07-28 17:44 UTC, wengxt requested changes

2023-07-28 17:44 UTC, wengxt commented on qt5/dbusaddons/fcitxqtinputcontextproxy.cpp
> +    return d->icproxy_->IsVirtualKeyboardVisible();
This is a synchronous dbus call. we should never do that.

Please implement a dbus signal and cache the state in input context instead.

2023-07-28 17:47 UTC, wengxt commented
Current approach for implement isInputPanelVisible is bad since it will initiate a dbus function call everytime it is invoked.

Also QPlatformInputContext::emitInputPanelVisibleChanged is not called.

You should implement a event in VirtualKeyboardVisibilityChanged Event in fcitx, then make dbusfrontend subscribe to it, and emit the dbus signal when the event happens, then make qt monitor the signal and cache the last known visiblity value.

2023-07-30 01:59 UTC, kingysu commented
> Current approach for implement isInputPanelVisible is bad since it will initiate a dbus function call everytime it is invoked.
> 
> Also QPlatformInputContext::emitInputPanelVisibleChanged is not called.
> 
> You should implement a event in VirtualKeyboardVisibilityChanged Event in fcitx, then make dbusfrontend subscribe to it, and emit the dbus signal when the event happens, then make qt monitor the signal and cache the last known visiblity value.

I have implemented  the new event for virtual keyboard's visibility in fcitx5.
The PR link is: [Add a new event for virtual keeyboard's visibility #837
](https://github.com/fcitx/fcitx5/pull/837)

2023-07-31 21:56 UTC, closed without merging